name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - run: git diff --name-only ${{ github.event.head_ref }} ${{ github.sha }}
      - uses: actions/setup-node@v1
      - run: npm install -g bats
      - run: bats -v
