name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - id: files
        uses: actions/checkout@v2
        run: |
                for changed_file in ${{ steps.files.outputs.all }}; do
                    echo "Do something with this ${changed_file}."
                done
      - uses: actions/setup-node@v1
      - run: npm install -g bats
      - run: bats -v
